# .pre-commit-config.yaml

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        name: ruff-fix
        args: ["check", "--fix", "--show-files"]
        additional_dependencies: []
      - id: ruff
        name: ruff-verify
        args: ["check", "--show-files"]
        additional_dependencies: []

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["-r", "cli", "InfraBox.py"]
